#!/usr/bin/expect -f

set prompt "#"
set controller [lindex $argv 0]
set command [lindex $argv 1]
set expecting [lindex $argv 2]

spawn bluetoothctl
expect -re $prompt
send "select $controller\r"
expect -re $controller
send "$command\r"
sleep 0.05
expect -re "$expecting"
send -- "exit\r"
expect eof
