#!/bin/bash
config_dir=~/.config/bluetooth
temp_file=/tmp/bluetooth
script_title="Bluetooth control"
menu_actions="Connect\nDisconnect\nPower off"

send_response () {
	notify-send "$script_title" "$(cat /tmp/bluetooth | sed 's/\x1B\[[0-9;]*[JKmsu]//g' | sed 's/\r/\n/g' | grep $1)"
}

mkdir -p "$config_dir"
# Setting default controller
controller_file="$config_dir/default_controller"
if test -f "$controller_file";
then
	controller=$(cat "$controller_file")
else
	controller=$(bluetoothctl list | dmenu -l 10 -p "Select bluetooth controller" | awk '{print $2}')
	echo $controller > "$controller_file"
fi

controller_status=$(bluetoothctl show $controller | awk '/Powered/ {print $2}')

# Powering on controller
if [ $controller_status = "no" ]
then
	response=$(echo -e "No\nYes" | dmenu -p "Enable bluetooth?")
	if [ $response = 'Yes' ]
	then
		bluetooth-control-command $controller "power on" "Changing power on" > $temp_file
		send_response Changing
	fi
fi
controller_status=$(bluetoothctl show $controller | awk '/Powered/ {print $2}')
if [ $controller_status = "no" ]
then
	exit 0
fi

# Handling actions
action=$(printf "$menu_actions" | dmenu -l 10 -p "Bluetooth control")
case $action in
	"Power off")
		for device in $(bluetoothctl devices | awk '{print $2}')
		do
			bluetooth-control-command $controller "disconnect $device"
		done
		bluetooth-control-command $controller "power off" "Changing power" > $temp_file
		send_response Changing
		;;
	"Connect")
		chosen_device_id=$(bluetoothctl devices | dmenu -l 10 -p "Device to connect" | awk '{print $2}')
		bluetooth-control-command $controller "connect $chosen_device_id" "uccessful" > $temp_file
		send_response "uccessful"
		;;
	"Disconnect")
		chosen_device_id=$(bluetoothctl devices | dmenu -l 10 -p "Device to connect" | awk '{print $2}')
		bluetooth-control-command $controller "disconnect $chosen_device_id" "uccessful" > $temp_file
		send_response "uccessful"
esac
