#!/bin/bash
configdir="$HOME/.config/todo/"
todofile="$HOME/.cache/todo.txt"
calendarfile="$HOME/.cache/todo-ical.ics"
clean_bg="$configdir/bg.png"
edited_bg="$configdir/edited-bg.png"
text_color="silver"
text_size=150

mkdir $configdir 2> /dev/null
test ! -f $wallpaper && cp $HOME/.config/wall.png $clean_bg
touch $todofile

vim $todofile

display_tasks() {
		taskcount=$(wc -l $todofile | awk '{print $1}')
		if [ $taskcount != 0 ]; then
			convert $clean_bg -fill $text_color -gravity Center -pointsize $text_size -annotate 0 $taskcount $edited_bg
			setbg $edited_bg
		else
			setbg $clean_bg
		fi
}

first_line=$(head -n 1 "$todofile")
case $first_line in
	"HIDE")
		setbg $clean_bg
		;;
	"LOAD")
		wget -O $calendarfile $CALENDAR_URL
		todo-ical $calendarfile > $todofile
		display_tasks
		;;
	*)
		display_tasks
esac
