#!/bin/bash
configdir="$HOME/.config/todo"
cachedir="$HOME/.cache/todo"
todofile="$cachedir/todo.txt"
clean_bg="$configdir/bg.png"
edited_bg="$configdir/edited-bg.png"
text_color="silver"
text_size=150

display_tasks() {
		taskcount=$(wc -l $todofile | awk '{print $1}')
		if [ $taskcount != 0 ]; then
			convert $clean_bg -fill $text_color -gravity Center -pointsize $text_size -annotate 0 $taskcount $edited_bg
			xwallpaper --zoom $edited_bg
		else
			xwallpaper --zoom $clean_bg
		fi
}

load_from_calendar() {
	rm -f $cachedir/ical/*
	for url in $CALENDAR_URLS; do
		wget -P $cachedir/ical $url
	done
	todo-ical $cachedir/ical >> $todofile
	display_tasks
}

mkdir $configdir 2> /dev/null
mkdir $cachedir 2> /dev/null
mkdir $cachedir/ical 2> /dev/null
test ! -f $wallpaper && cp $HOME/.config/wall.png $clean_bg
touch $todofile

if [ "$1" == 'load' ]; then
	load_from_calendar
	exit
fi

vim $todofile

first_line=$(head -n 1 "$todofile")
case $first_line in
	"HIDE")
		xwallpaper --zoom $clean_bg
		;;
	"LOAD")
		load_from_calendar
		;;
	*)
		display_tasks
esac
